### ISSUE TITLE
Home Assistant integration

### ISSUE THREAD

**Issue by weidi** [frwickst/pyhuum#1]
Hi, 
i found your python lib for humm when trying to build a Home Assistant integration for Huum. I then tried to figure out how HA integrations and specifically python works but i did not manage to get it working. 
Do you know HA and would you mind implementing an integration for it to support huum saunas ?

https://community.home-assistant.io/t/integration-of-huum-uku-wifi/312102/6

BR

**Comment by frwickst** [comment]
Hi @weidi!
This package was created to be used with an intergration to the Huum sauna that I'm working on. I have unfortunately not found time to complete the integration yet, however it is very close to being done.
In other words, this package itself can not be used with HA, but it can be used to create the integration that is needed for HA. Once I find the time to finish up the integration, I will create a PR straight to HA and hopefully once the reviews are done, you will be able to integrate with the sauna straight from HA :)

**Comment by frwickst** [comment]
Integration PR created https://github.com/home-assistant/core/pull/72674
