### ISSUE TITLE
Type Mismatch for payment_end_date in HuumStatusResponse

### ISSUE THREAD

**Issue by viilup** [frwickst/pyhuum#7]
## Description
The `pyhuum` library encounters a type mismatch error when parsing the `payment_end_date` field from a Huum device response. The schema defined in `schemas.py` expects an `int` or `None` for the `payment_end_date`, but the device is returning a datetime string (`'2021-06-25 23:59:59'`). This causes a failure when attempting to deserialize the device response into a `HuumStatusResponse` object.

## Environment
- Python Version: 3.12

## Steps to Reproduce
1. Invoke the `status()` method to fetch the status of a Huum device.
2. Observe the error during the deserialization process.

## Expected Behavior
The library should correctly handle the datetime string returned by the device for the `payment_end_date` field, possibly by converting it into an integer timestamp or changing the field's expected type to accommodate datetime strings.

## Actual Behavior
An error is thrown due to a type mismatch, expecting an `Optional[int]` for the `payment_end_date` but receiving a datetime string.

## Error Logs
Logger: homeassistant.components.huum.config_flow
Source: components/huum/config_flow.py:45
Integration: Huum (documentation, issues)
First occurred: 22:03:52 (1 occurrences)
Last logged: 22:03:52

Unknown error
Traceback (most recent call last):
  File "<string>", line 75, in __mashumaro_from_dict__
ValueError: invalid literal for int() with base 10: '2021-06-25 23:59:59'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/huum/config_flow.py", line 45, in async_step_user
    await huum_handler.status()
  File "/usr/local/lib/python3.12/site-packages/huum/huum.py", line 165, in status
    return HuumStatusResponse.from_dict(json_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 77, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "payment_end_date" of type Optional[int] in HuumStatusResponse has invalid value '2021-06-25 23:59:59'

**Comment by frwickst** [comment]
Thank you for reporting the issue. I will take a round later this weekend to try to fix some of the issues that have been appearing so far with this library and the HA integration.

**Comment by frwickst** [comment]
In this case, I did not have a `payment_end_date` ever in my response and could not test that properly, so nice that I could get a proper test now with your setup, thank you for that!

**Comment by viilup** [comment]
I was assuming that this was the case. Thanks for looking into that!
